# Generated by Django 5.2.7 on 2025-11-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """Updated the possible length of type fields for the objects."""

    dependencies = [
        ("project_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lightsource",
            name="distribution_type",
            field=models.CharField(default="normal", max_length=50),
        ),
        migrations.AlterField(
            model_name="lightsource",
            name="light_source_type",
            field=models.CharField(default="sun", max_length=50),
        ),
        migrations.AlterField(
            model_name="receiver",
            name="receiver_type",
            field=models.CharField(default="planar", max_length=50),
        ),
    ]
